# Config file for automatic testing at travis-ci.org
language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
cache: npm
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - pip install wheel
script:
- make dist

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
#    on:
#      tags: true
