# Config file for automatic testing at travis-ci.org
language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- cd web
- ng build --prod
