# Config file for automatic testing at travis-ci.org
language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
cache: npm
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- cd web
- npm install
- ng build --prod
- cd dist/web/
- zip -r web.zip *

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: web.zip
#    on:
#      tags: true
