name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          pip install wheel
      - name: Make
        run: |
          make dist
          ls -l dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
